version: '2'
services:
  golang:
    image: go-tools
    env_file: .env
    ports:
      - 7006:1323
    volumes:
      - ./:/go/src/app/
    working_dir: /go/src/app/
    command: go run main.go
  dep:
    image: go-tools
    volumes:
    - ./:/go/src/app
    working_dir: /go/src/app
    command: dep ensure -v
